package com.xepicgamerzx.hotelier.storage.dao;

import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Update;

/**
 * Base interface for all DAOs, implementing insert, update and delete functions.
 *
 * @param <Q> insert return type (Accepts either Void or List<Long>.
 * @param <T> Entity being handled by the DAO.
 */
@SuppressWarnings("unchecked")
public interface BaseDao <Q, T>{
    /**
     * Insert entity into their corresponding table in the database. Replace on conflict.
     *
     * @param obj T entities to be inserted into their corresponding table.
     * @return autogenerated IDs if applicable.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    Q insert(T... obj);

    /**
     * Update entity in their corresponding table in the database.
     *
     * @param obj T entities to be updated.
     * @return int number of entities successfully updated.
     */
    @Update
    int update(T... obj);

    /**
     * Delete entity from their corresponding table.
     *
     * @param obj T entity to be deleted.
     */
    @Delete
    void delete(T obj);
}
