package com.xepicgamerzx.hotelier.storage;

import android.app.Application;

import androidx.annotation.NonNull;

import com.xepicgamerzx.hotelier.objects.Address;
import com.xepicgamerzx.hotelier.objects.Hotel;
import com.xepicgamerzx.hotelier.objects.HotelAmenities;
import com.xepicgamerzx.hotelier.objects.HotelAmenitiesCrossRef;
import com.xepicgamerzx.hotelier.objects.HotelAmenity;
import com.xepicgamerzx.hotelier.objects.HotelRoom;
import com.xepicgamerzx.hotelier.storage.dao.HotelAmenitiesCrossDao;
import com.xepicgamerzx.hotelier.storage.dao.HotelDao;

import java.util.List;

/**
 * A class to manage all the hotels in our database.
 */
public class HotelManager implements LongManager<Hotel> {
    private static volatile HotelManager INSTANCE;

    private final HotelierDatabase db;
    private final HotelDao hotelDao;
    private final HotelAmenitiesCrossDao hotelAmenitiesCrossDao;
    private final RoomManager roomManager;

    private HotelManager(Application application) {
        db = HotelierDatabase.getDatabase(application);
        hotelDao = db.hotelDao();
        hotelAmenitiesCrossDao = db.hotelAmenitiesCrossDao();

        roomManager = RoomManager.getManager(application);
    }

    private HotelManager(HotelierDatabase dbInstance) {
        db = dbInstance;
        hotelDao = db.hotelDao();
        hotelAmenitiesCrossDao = db.hotelAmenitiesCrossDao();

        roomManager = RoomManager.getManager(dbInstance);
    }

    public static HotelManager getManager(Application application) {
        if (INSTANCE == null) {
            INSTANCE = new HotelManager(application);
        }

        return INSTANCE;
    }

    public static HotelManager getManager(HotelierDatabase dbInstance) {
        if (INSTANCE == null) {
            INSTANCE = new HotelManager(dbInstance);
        }

        return INSTANCE;
    }

    /**
     * Creates hotel object and inserts it to the database. (No rooms)
     *
     * @param name      String name of the hotel.
     * @param address   Address object associated with the hotel.
     * @param starClass Int star class of the hotel
     * @return Hotel object created.
     */
    @NonNull
    public Hotel createHotel(String name, Address address, int starClass) {
        Hotel hotel = new Hotel(name, address, starClass);
        Long[] id = insert(hotel);
        return get(id).get(0);
    }

    /**
     * Creates hotel object and inserts it to the database. Also associates a list of hotel rooms
     * with the hotel object and inserts these associations to the HotelRoom database.
     *
     * @param name       String name of the hotel.
     * @param address    Address object associated with the hotel.
     * @param starClass  Int star class of the hotel
     * @param hotelRooms List of HotelRooms to be associated with the Hotel object.
     * @return Hotel object created.
     */
    @NonNull
    public Hotel createHotel(String name, Address address, int starClass, HotelRoom... hotelRooms) {
        Hotel hotel = createHotel(name, address, starClass);

        for (HotelRoom hotelRoom : hotelRooms) {
            roomManager.setHotelID(hotel, hotelRoom);
        }

        return hotel;
    }

    /**
     * Inserts the Hotel(s) to the Hotel database.
     *
     * @param hotel Hotel object(s) to be saved.
     * @return Long[], autogenerated HotelID of the Hotel(s) saved.
     */
    @Override
    public Long[] insert(Hotel... hotel) {
        return hotelDao.insertHotels(hotel).toArray(new Long[0]);
    }


    /**
     * Updates Hotel object(s) in the database.
     *
     * @param hotel Hotel object(s) to be updated in the database.
     */
    @Override
    public void update(Hotel... hotel) {
        hotelDao.updateHotels(hotel);
    }

    @NonNull
    public HotelAmenity createHotelAmenity(String amenityName) {
        HotelAmenity hotelAmenity = new HotelAmenity(amenityName);
        hotelAmenitiesCrossDao.insertHotelAmenities(hotelAmenity);
        return hotelAmenity;
    }

    @NonNull
    public HotelAmenity createHotelAmenity(HotelAmenities amenity) {
        HotelAmenity hotelAmenity = new HotelAmenity(amenity);
        hotelAmenitiesCrossDao.insertHotelAmenities(hotelAmenity);
        return hotelAmenity;
    }

    public void addAmenityToHotel(Hotel hotel, HotelAmenity hotelAmenity) {
        HotelAmenitiesCrossRef hotelAmenitiesCrossRef = new HotelAmenitiesCrossRef(hotel, hotelAmenity);
        hotelAmenitiesCrossDao.insertHotelAmenitiesCrossRef(hotelAmenitiesCrossRef);
    }

    /**
     * Get hotels with matching hotel IDs.
     *
     * @param hotelID Long hotelIDs to be used as search keys.
     * @return List of Hotels with matching HotelIDs.
     */
    @Override
    public List<Hotel> get(Long... hotelID) {
        return hotelDao.getHotels(hotelID);
    }

    /**
     * Gets all hotels in the Hotel database.
     *
     * @return List of the Hotels in the Hotel database.
     */
    @Override
    public List<Hotel> getAll() {
        return hotelDao.getAllHotels();
    }

    /**
     * Closes the manager if already open.
     */
    @Override
    public void close() {
        INSTANCE = null;
    }
}
