    name: GitHub Android Build and Test Workflow


    on: [push]
    


    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 1.11
              uses: actions/setup-java@v1
              with:
                java-version: 1.11
                
            - uses: actions/checkout@v2
            - uses: android-actions/setup-android@v2
            - run: sdkmanager "platform-tools" "platforms;android-30"
            - run: echo $ANDROID_SDK_ROOT
            
            - name: Build with Gradle
              run: ./gradlew build        
      
